# Generated by Django 3.0.3 on 2020-02-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0002_auto_20200211_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='midi',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
